### ISSUE TITLE
SuoeriorSkyblock2 | [ ERROR ]

### ISSUE THREAD

**Issue by NieToNieJa** [OmerBenGera/WildLoaders#1]
I wrote about it on discord but nobody managed to deal with this problem and they sent me here, maybe you can help me.
Plugin makes so much errors (if i deleted the plugin when the server start working normal)
Error link: https://pastebin.pl/view/d6f3674a

**Comment by OmerBenGera** [comment]
Please make an issue on the plugin's github and not here.
