### ISSUE TITLE
Loader Duration no longer ticks down

### ISSUE THREAD

**Issue by Spaex** [OmerBenGera/WildLoaders#2]
The Chunkloader no longer ticks down in the 1.16 Version of Minecraft. The Time Left Label always stays on 1 day remaining since Paper 349's change "Optimized tick ready check". I've reported this issue to Paper and they (lukalt) answered the following:

> 
> 
> I guess this is caused because the plugin creates a new tile entity which is registered in a different way than normal tile entities causing TileEntity.getCurrentChunk() to return null as the tile entity is never bound to a specific chunj. I'm not quite sure if this could be fixed in Paper without reverting the optimization. The easiest solution would be to use world.a(tileEntityChunkLoader) here
> https://github.com/OmerBenGera/WildLoaders/blob/master/v1_16_R3/src/main/java/com/bgsoftware/wildloaders/nms/NMSAdapter_v1_16_R3.java#L197

Since I don't have access to the private repo neither the EpicSpawners Plugin I want to report this here so it maybe could be fixed in near future:)

**Comment by OmerBenGera** [comment]
Interesting, I am gonna check that out!
Thanks for reporting!

**Comment by Spaex** [comment]
No problem!:) Hope you have a nice day!:)

**Comment by OmerBenGera** [comment]
Fixed in build #4
