### ISSUE TITLE
 Chunk which doesn't unload

### ISSUE THREAD

**Issue by nivcoo** [OmerBenGera/WildLoaders#3]
Hello, when we place Loader and break it after the spawner and chunk still loaded. So we can have infinite chunk loader until the server restart.

**Comment by OmerBenGera** [comment]
Use latest dev build. Does it still occur?
If it does, answer the following questions:
- How to replicate the issue?
- What's your spigot version?
- Does it happen on a server with only WildLoaders installed?

**Comment by nivcoo** [comment]
I use the WildLoaders-b4.jar in 1.12.2 (Kspigot), to replicate the bug you have to place loader with spawner and break it, after that you can look spawner will spawn while the players are not connected or far from the spawner. I have check the DB and the loader is correctly removed.

**Comment by OmerBenGera** [comment]
Have you tried it on regular Paper?

**Comment by nivcoo** [comment]
Yes in my test server

**Comment by OmerBenGera** [comment]
Do you have wildstacker installed by any chance?

**Comment by nivcoo** [comment]
No i haven’t

**Comment by OmerBenGera** [comment]
Check out latest dev build, should be fixed

**Comment by nivcoo** [comment]
Yes I will test thank you, looking at the database I noticed that the npc table was not empty at the uuid level but I thought it was normal.

**Comment by OmerBenGera** [comment]
Have you tried it?

**Comment by nivcoo** [comment]
Yes it works

**Comment by OmerBenGera** [comment]
Great :)
